"""changed name for customer

Revision ID: 56f4ca681e18
Revises: 73b16c7ba02f
Create Date: 2024-08-23 16:08:50.334078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f4ca681e18'
down_revision = '73b16c7ba02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personel')
    op.drop_table('musteri')
    op.drop_table('randevu')
    op.drop_table('paket')
    op.drop_table('rapor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rapor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ekspertiz_tarihi', sa.DATE(), nullable=False),
    sa.Column('arac_plaka', sa.VARCHAR(length=10), nullable=False),
    sa.Column('sasi_no', sa.VARCHAR(length=17), nullable=False),
    sa.Column('marka', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model_yili', sa.INTEGER(), nullable=False),
    sa.Column('musteri_id', sa.INTEGER(), nullable=False),
    sa.Column('paket_id', sa.INTEGER(), nullable=False),
    sa.Column('islem', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.ForeignKeyConstraint(['paket_id'], ['paket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ad', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fiyat', sa.FLOAT(), nullable=False),
    sa.Column('icerikler', sa.VARCHAR(length=255), nullable=False),
    sa.Column('aktif', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randevu',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('musteri_id', sa.INTEGER(), nullable=False),
    sa.Column('tarih', sa.DATE(), nullable=False),
    sa.Column('saat', sa.TIME(), nullable=False),
    sa.Column('marka', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hatirlatma_gonderildi_mi', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musteri',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ad_soyad', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telefon_no', sa.VARCHAR(length=15), nullable=False),
    sa.Column('eposta', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ad_soyad', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sifre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telefon_no', sa.VARCHAR(length=15), nullable=False),
    sa.Column('departman', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
