"""initial migration

Revision ID: 73b16c7ba02f
Revises: 
Create Date: 2024-08-23 13:33:47.457534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b16c7ba02f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musteri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=100), nullable=False),
    sa.Column('telefon_no', sa.String(length=15), nullable=False),
    sa.Column('eposta', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('fiyat', sa.Float(), nullable=False),
    sa.Column('icerikler', sa.String(length=255), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=100), nullable=False),
    sa.Column('sifre', sa.String(length=100), nullable=False),
    sa.Column('telefon_no', sa.String(length=15), nullable=False),
    sa.Column('departman', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randevu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('saat', sa.Time(), nullable=False),
    sa.Column('marka', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('hatirlatma_gonderildi_mi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ekspertiz_tarihi', sa.Date(), nullable=False),
    sa.Column('arac_plaka', sa.String(length=10), nullable=False),
    sa.Column('sasi_no', sa.String(length=17), nullable=False),
    sa.Column('marka', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('model_yili', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('paket_id', sa.Integer(), nullable=False),
    sa.Column('islem', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.ForeignKeyConstraint(['paket_id'], ['paket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rapor')
    op.drop_table('randevu')
    op.drop_table('personel')
    op.drop_table('paket')
    op.drop_table('musteri')
    # ### end Alembic commands ###
