"""create enums, vehicle, agent, vehicleowner

Revision ID: 8fe4b2fb63db
Revises: 56f4ca681e18
Create Date: 2024-08-25 01:03:45.557193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe4b2fb63db'
down_revision = '56f4ca681e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Commented out since columns already exist
    # with op.batch_alter_table('customer', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('tc_tax_number', sa.String(length=11), nullable=True))
    #     batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('registration_document_seen', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key('fk_report_created_by_staff', 'staff', ['created_by'], ['id'])

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_staff_branch_id', 'branch', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint('fk_staff_branch_id', type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_created_by_staff', type_='foreignkey')
        batch_op.drop_column('registration_document_seen')
        batch_op.drop_column('created_by')

    # Commented out since columns already exist
    # with op.batch_alter_table('customer', schema=None) as batch_op:
    #     batch_op.drop_column('address')
    #     batch_op.drop_column('tc_tax_number')

    # ### end Alembic commands ###
